Blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView , DetailView , UpdateView , DeleteView

app_name = 'Blog'

urlpatterns = [

    path('', BlogListView.as_view(), name='home'),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', DeleteView.as_view(), name='delete'),

]

core/urls.py
#Imports
from django.contrib import admin
from django.urls import path , include
from .views import HomeView

#UrlsPatterns
urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),

    path('blog/', include('Blog.urls', namespace='Blog')),

    # path("__reload__/", include("django_browser_reload.urls")),

]
 

Blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

# class User(models.Model):
#     first_name = models.CharField(max_length=250)
#     last_name = models.CharField(max_length=250)
#     birthday = models.DateField()
#     username = models.CharField(max_length=100)
#     email = models.EmailField(min_length= 6,max_length=70)

#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.name

Blog/forms.py
from django import forms
from .models import Post

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

Blog/views.py
from django.shortcuts import render , redirect , get_object_or_404
from django.views.generic import View , UpdateView , DeleteView

from .forms import CreatePostForm
from .models import Post
from django.urls import reverse_lazy


# Create Posts List View
class BlogListView(View):
    
    def get( self , request , *args , **kwargs ):

        posts = Post.objects.all()

        context = {
            'posts': posts
        }

        return render( request , 'blog_list.html' , context )

#Create a new post view
class BlogCreateView(View):

    def get( self , request , *args , **kwargs ):

        form = CreatePostForm()

        context = {
            'form': form
        }


        return render( request , 'blog_create.html' , context )

    def post( self , request , *args , **kwargs ):

        if request.method == 'POST':
            form = CreatePostForm( request.POST )
            if form.is_valid():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']

                p, created = Post.objects.get_or_create( title = title , content = content )
                p.save()

                return redirect('Blog:home')
        context = {

        }
        return render( request , 'blog_create.html' , context )


class DetailView(View):

    def get( self , request , pk , *args , **kwargs ):

        post = get_object_or_404( Post , pk = pk )

        context = {
            'post': post
        }
        return render( request , 'detail.html', context )


class UpdateView(UpdateView):

    model = Post
    fields = ['title', 'content']
    template_name = 'blog_update.html'

    def get_success_url(self):
        
        pk = self.kwargs['pk']

        return reverse_lazy('Blog:detail', kwargs={'pk': pk})


class DeleteView(DeleteView):

    model = Post
    template_name = 'blog_delete.html'

    def get_success_url(self):
        return reverse_lazy('Blog:home')

    
    

core/views.py
from django.views.generic import View
from django.shortcuts import render


class HomeView(View):
    def get(self, request):

        context = {

        }

        return render(request, 'index.html', context)

templates/base.html
{% load static %}
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    {% tailwind_css %}
    

</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/blog_create.html
<form method="POST" >
{% csrf_token %}
title{{ form.title }}
<br>
content{{ form.content }}
<button type="submit">Submit</button>
</form>

templates/blog_delete.html
<form method="POST" >
{% csrf_token %}
{{ form }}
<button type="submit">Delete</button>
</form>

templates/blog_list.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Blog list</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>

    
    <body>
        <br>
        {% for post in posts %}
        <a href="{% url 'Blog:detail' post.id %}">{{ post.title }}</a>
        <a href="{% url 'Blog:update' post.id %}">Update</a>
        <a href="{% url 'Blog:delete' post.id %}">Delete</a>
        {% endfor %}
        </br>
        <a href="{% url 'Blog:create' %}">Create</a>
    </body>
</html>

templates/blog_update.html
<form method="POST" >
{% csrf_token %}
title{{ form.title }}
<br>
content{{ form.content }}
<button type="submit">Update</button>
</form>

templates/detail.html
{{ post.title }}
<br>
{{ post.content }}

templates/index.html
{% extends 'base.html' %}
    {% load static %}
    <audio src="{% static 'audio/audio.mp3' %}" loop="3" autoplay="true"/>
    {% block content %}
    
    hola visita mi 
   
    <audio src="audio.mp3"></audio>
        Blog aqui
    
    </a>
    {% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>